export const styles = {
  modalHeader: {
    color: "#fff",
    textAlign: "center",
    marginBottom: "20px",
    fontSize: "24px",
    fontWeight: "bold",
  },
  group: {
    marginBottom: "20px",
    padding: "15px",
    borderRadius: "10px",
    backgroundColor: "#1e1e1e",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.4)",
  },
  groupHeader: {
    fontSize: "18px",
    fontWeight: "bold",
    color: "#4caf50",
    marginBottom: "10px",
    borderBottom: "1px solid #4caf50",
    paddingBottom: "5px",
  },
  inputContainer: {
    display: "flex",
    alignItems: "center",
    marginBottom: "15px",
    padding: "5px 0",
  },
  inputLabel: {
    color: "#fff",
    marginRight: "10px",
    fontWeight: "bold",
  },
  inputField: {
    width: "100px",
    padding: "8px",
    borderRadius: "6px",
    border: "1px solid #555",
    textAlign: "center",
    backgroundColor: "#2c2c2c",
    color: "#fff",
    fontSize: "14px",
    boxShadow: "inset 0 1px 3px rgba(0, 0, 0, 0.2)",
  },
  checkboxContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
  },
  applyButton: {
    backgroundColor: "#4caf50",
    color: "#fff",
    padding: "12px 25px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "18px",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.3)",
    transition: "background-color 0.3s ease, transform 0.2s ease",
    marginTop: "25px",
    display: "block",
    marginLeft: "auto",
    marginRight: "auto",
  },
  applyButtonHover: {
    backgroundColor: "#3e8e41",
  },
};