export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '50vh',
    overflow: 'hidden',
    borderRadius: '8px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.5)',
  },
  header: {
    padding: '8px 16px',
    backgroundColor: '#3a3a3a',
    background: 'linear-gradient(145deg, #4a4a4a, #2a2a2a)',
    borderBottom: '2px solid #444',
    fontSize: '18px',
    fontWeight: 'bold',
    fontFamily: 'Consolas, "Courier New", monospace',
    color: '#f0f0f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '40px',
  },
  content: {
    flex: 1,
    backgroundColor: '#1f1f1f',
    color: '#e0e0e0',
    border: '1px solid #3a3a3a',
    padding: '16px',
    borderRadius: '0 0 12px 12px',
  },
};
