export const styles = {
  container: {
    padding: 0,
  },
  toolbar: {
  },
  loading: {
    color: '#999',
    fontSize: '14px',
    textAlign: 'center',
  },
  error: {
    color: '#e57373',
    fontSize: '14px',
    textAlign: 'center',
  },
  input: {
    width: 'calc(100% - 20px)',
    padding: '10px',
    margin: '10px 0',
    borderRadius: '6px',
    border: '1px solid #444',
    backgroundColor: '#2b2b2b',
    color: '#e0e0e0',
    fontSize: '14px',
    boxSizing: 'border-box',
  },
  dialogHeader: {
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '8px',
  },
  dialog: {
    maxWidth: '400px',
    width: '90%',
    backgroundColor: '#2b2b2b',
    padding: '20px',
    borderRadius: '8px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.25)',
    margin: '0 auto',
  },
  actions: {
    display: 'flex',
    gap: '8px',
  },
  uploadProgress: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px',
    margin: '10px 0',
    backgroundColor: '#1e1e1e',
    color: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.2)',
    fontSize: '14px',
    fontWeight: 'bold',
    width: '100%',
  },
};
