const styles = {
  trigger: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '16px',
    color: '#fff',
    padding: '5px',
    borderRadius: '50%',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    transition: 'background-color 0.3s ease',
  },
  menu: {
    position: 'absolute',
    top: '40px',
    right: '0',
    background: '#1e1e1e',
    border: '1px solid #444',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    minWidth: '150px',
    zIndex: 1000,
    overflow: 'hidden',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px 15px',
    cursor: 'pointer',
    color: '#fff',
    backgroundColor: 'transparent',
    transition: 'background-color 0.3s ease, color 0.3s ease',
  },
  icon: {
    marginRight: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
  },
  menuItemHover: {
    backgroundColor: '#333',
    color: '#4caf50',
  },
};

export default styles;
